# Generated by Django 4.2.1 on 2023-06-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("manufacturer", models.CharField(choices=[("SKODA", "Skoda")])),
                (
                    "engine_type",
                    models.CharField(
                        choices=[
                            ("GAS", "Gas"),
                            ("DIESEL", "Diesel"),
                            ("ELECTRIC", "Electric"),
                        ]
                    ),
                ),
                ("energy_usage", models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
    ]
