# Generated by Django 4.2.1 on 2023-06-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartypes",
            name="energy_usage",
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
