# Generated by Django 4.2.1 on 2023-06-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_alter_cartypes_energy_usage"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartypes",
            name="emissions",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
