# Generated by Django 4.2.1 on 2023-06-02 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_cartypes_emissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField()),
            ],
        ),
        migrations.AlterField(
            model_name="cartypes",
            name="engine_type",
            field=models.CharField(
                choices=[
                    ("GAS", "Gas"),
                    ("DIESEL", "Diesel"),
                    ("ELECTRIC", "Electric"),
                    ("HYBRID", "Hybrid"),
                ]
            ),
        ),
        migrations.CreateModel(
            name="Drive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_plate", models.CharField()),
                ("distance_km", models.IntegerField()),
                ("odometer_end_km", models.IntegerField()),
                ("time_start", models.DateTimeField()),
                ("time_stop", models.DateTimeField()),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drives",
                        to="web.datafile",
                    ),
                ),
            ],
        ),
    ]
