# Generated by Django 4.2.1 on 2023-06-02 15:22

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_datafile_alter_cartypes_engine_type_drive"),
    ]

    operations = [
        migrations.AddField(
            model_name="drive",
            name="location_start",
            field=django.contrib.gis.db.models.fields.PointField(
                default=None, srid=4326
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="drive",
            name="location_stop",
            field=django.contrib.gis.db.models.fields.PointField(
                default=None, srid=4326
            ),
            preserve_default=False,
        ),
    ]
