# Generated by Django 4.2.1 on 2023-06-02 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0006_remove_drive_license_plate_cardrive_drive_car"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardrive",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="web.cartypes",
            ),
        ),
    ]
