# Generated by Django 4.2.1 on 2023-06-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0008_cardrive_odometer_km"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardrive",
            name="odometer_km",
            field=models.IntegerField(default=0),
        ),
    ]
