# Generated by Django 4.2.1 on 2023-06-02 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0009_alter_cardrive_odometer_km"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardrive",
            name="proposed_type",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proposed",
                to="web.cartypes",
            ),
        ),
        migrations.AddField(
            model_name="cardrive",
            name="year_made",
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
