# Generated by Django 4.2.1 on 2023-06-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0010_cardrive_proposed_type_cardrive_year_made"),
    ]

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("replace_min_age_years", models.PositiveIntegerField()),
                ("replace_min_odometer_km", models.PositiveIntegerField()),
                ("max_range_margin_km", models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="cartypes",
            name="emissions",
        ),
        migrations.RemoveField(
            model_name="cartypes",
            name="energy_usage",
        ),
        migrations.AddField(
            model_name="cartypes",
            name="emissions_fuel_per_km",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cartypes",
            name="max_range_km",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="cartypes",
            name="manufacturer",
            field=models.CharField(choices=[("SKODA", "Skoda"), ("VW", "Vw")]),
        ),
    ]
