# Generated by Django 4.2.1 on 2023-06-03 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0011_analysis_remove_cartypes_emissions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="file",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis",
                to="web.datafile",
            ),
            preserve_default=False,
        ),
    ]
