# Generated by Django 4.2.1 on 2023-06-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0012_analysis_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardrive",
            name="frozen",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cartypes",
            name="cost_new",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
