# Generated by Django 4.2.1 on 2023-06-03 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0013_cardrive_frozen_cartypes_cost_new"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="max_range_margin_km",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="cardrive",
            name="proposed_type",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proposed",
                to="web.cartypes",
            ),
        ),
    ]
