# Generated by Django 4.2.1 on 2023-06-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0015_remove_analysis_file_remove_cardrive_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drive",
            name="odometer_end_km",
        ),
        migrations.RemoveField(
            model_name="drive",
            name="time_start",
        ),
        migrations.RemoveField(
            model_name="drive",
            name="time_stop",
        ),
        migrations.AlterField(
            model_name="drive",
            name="distance_km",
            field=models.PositiveIntegerField(),
        ),
    ]
