# Generated by Django 4.2.1 on 2023-06-08 13:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0016_remove_drive_odometer_end_km_remove_drive_time_start_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drive",
            name="distance_km",
        ),
    ]
