# Generated by Django 4.2.1 on 2023-06-09 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0017_remove_drive_distance_km"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cardrive",
            name="odometer_km",
        ),
    ]
