---

on:
  push:
    branches:
      - "main"

jobs:
  setup-build-deploy:
    runs-on: "ubuntu-latest"

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: "Git Checkout"
        uses: "actions/checkout@v3"

      # Configure Workload Identity Federation via a credentials file.
      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          token_format: "access_token"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ vars.GCP_LOCATION }}-docker.pkg.dev

      - name: "Build and push container"
        run: |-
          docker build -t "${{ vars.GCP_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ vars.APP_NAME }}/${{ vars.APP_NAME }}:${{ github.ref_name }}" .
          docker push "${{ vars.GCP_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ vars.APP_NAME }}/${{ vars.APP_NAME }}:${{ github.ref_name }}"

      - name: "Deploy Cloud Run"
        uses: "google-github-actions/deploy-cloudrun@v1"
        with:
          service: "greencars-${{ github.ref_name }}"
          image: "${{ vars.GCP_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ vars.APP_NAME }}/${{ vars.APP_NAME }}:${{ github.ref_name }}"
          region: "${{ vars.GCP_LOCATION }}"
          flags: "--set-cloudsql-instances=${{ secrets.GCP_CLOUD_SQL_HOST }} --cpu-boost --memory=1Gi --cpu=1000m --timeout=120"
          env_vars: |
            DJANGO_SETTINGS_MODULE=cars.settings.gcp
            GCP_CLOUD_SQL_NAME=greencars
            GCP_CLOUD_SQL_USER=greencars
            GCP_CLOUD_SQL_PASS=${{ secrets.GCP_CLOUD_SQL_PASS }}
            GCP_CLOUD_SQL_HOST=/cloudsql/${{ secrets.GCP_CLOUD_SQL_HOST }}
            GCP_BUCKET_STATIC=greencars-static-${{ github.ref_name }}